download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",getwd(),method="curl")
unzip("household_power_consumption.zip")
data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
newData <- subset(data,Date=="1/2/2007" | Date=="2/2/2007")
time <- paste(newData$Date,newData$Time,sep=" ")
time <- strptime(time,format = "%d/%m/%Y %H:%M:%S")
png("Plot3.png",width = 480, height = 480)
plot(time,as.numeric(paste(newData$Sub_metering_1)),type="l",ylab = "Energy sub metering")
lines(time,as.numeric(paste(newData$Sub_metering_2)),col = "red")
lines(time,as.numeric(paste(newData$Sub_metering_3)),col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lwd = 1,lty = c(1,1,1))
dev.off()