download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",getwd(),method="curl")
unzip("household_power_consumption.zip")
data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
newData <- subset(data,Date=="1/2/2007" | Date=="2/2/2007")
png("Plot1.png",width = 480, height = 480)
hist(as.numeric(paste(newData$Global_active_power)),col="red",xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()