download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",getwd(),method="curl")
unzip("household_power_consumption.zip")
data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
newData <- subset(data,Date=="1/2/2007" | Date=="2/2/2007")
time <- paste(newData$Date,newData$Time,sep=" ")
time <- strptime(time,format = "%d/%m/%Y %H:%M:%S")
png("Plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(time,as.numeric(paste(newData$Global_active_power)),ylab = "Global Active Power",type="l", xlab = "")
plot(time,as.numeric(paste(newData$Voltage)),ylab = "Voltage",type="l", xlab = "datetime")
plot(time,as.numeric(paste(newData$Sub_metering_1)),ylab = "Energy sub meter",type="l", xlab = "")
lines(time,as.numeric(paste(newData$Sub_metering_2)),col="red")
lines(time,as.numeric(paste(newData$Sub_metering_3)),col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = 1, bty = "n")
plot(time,as.numeric(paste(newData$Global_reactive_power)),ylab = "Global_reactive_power",type="l", xlab = "datetime")
dev.off()